#define OPT_REV_RANKMAP_ITER 1
#define OPT_ZERO_RANKMAP_INLINE 1
#define OPT_PREALLOC_TO_DELETE 0
#define OPT_PREALLOC_RANKMAP 0
#define OPT_ARRAY_OVER_MAP_RANKMAP 1
#define OPT_INLINE_EVERYTHING 0
#define OPT_QUAD_MULTIPLIER 0
#define OPT_DEC_KEY_RANK_DEC 2
